// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEAEpYxbuPIXVj-PpWLmFeYExOMnVQSRQ',
    appId: '1:1030040746214:web:d4dc54b7be2453ece82327',
    messagingSenderId: '1030040746214',
    projectId: 'financeapp-ef4bf',
    authDomain: 'financeapp-ef4bf.firebaseapp.com',
    storageBucket: 'financeapp-ef4bf.appspot.com',
    measurementId: 'G-VQ2WL820M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0JL2qOymp69F9hv-4SxETQrE_ajxSLzo',
    appId: '1:1030040746214:android:7dd2684270f4c164e82327',
    messagingSenderId: '1030040746214',
    projectId: 'financeapp-ef4bf',
    storageBucket: 'financeapp-ef4bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNfz4rNvQUxjOdkUyNNu7Z6u50EjPS52s',
    appId: '1:1030040746214:ios:cadaf54bd8ad57f6e82327',
    messagingSenderId: '1030040746214',
    projectId: 'financeapp-ef4bf',
    storageBucket: 'financeapp-ef4bf.appspot.com',
    iosClientId: '1030040746214-7e08ss505ltgruoccm007ka0bnqh9ved.apps.googleusercontent.com',
    iosBundleId: 'com.expensesspy.expensesspy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNfz4rNvQUxjOdkUyNNu7Z6u50EjPS52s',
    appId: '1:1030040746214:ios:cadaf54bd8ad57f6e82327',
    messagingSenderId: '1030040746214',
    projectId: 'financeapp-ef4bf',
    storageBucket: 'financeapp-ef4bf.appspot.com',
    iosClientId: '1030040746214-7e08ss505ltgruoccm007ka0bnqh9ved.apps.googleusercontent.com',
    iosBundleId: 'com.expensesspy.expensesspy',
  );
}
